// <auto-generated />
using System;
using IPass.EFRepositories.IPassContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IPass.EFRepositories.Migrations
{
    [DbContext(typeof(MyMemoryDbContext))]
    [Migration("20220706190735_History")]
    partial class History
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("MEM")
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IPass.Domain.PasswordDomain.Entities.EnvironmentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EnvironmentTypes", "MEM");
                });

            modelBuilder.Entity("IPass.Domain.PasswordDomain.Entities.Memory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EnvironmentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HostOrIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHostOrIpAddressSecure")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPortSecure")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUEmailSecure")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUserNameSecure")
                        .HasColumnType("bit");

                    b.Property<Guid>("MemoryTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Port")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidationEndAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidationEndAt");

                    b.Property<DateTime>("ValidationStartAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidationStartAt");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentTypeId");

                    b.HasIndex("MemoryTypeId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Memories", "LOG");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb.UseHistoryTable("MemoryHistories");
                            ttb
                                .HasPeriodStart("ValidationStartAt")
                                .HasColumnName("ValidationStartAt");
                            ttb
                                .HasPeriodEnd("ValidationEndAt")
                                .HasColumnName("ValidationEndAt");
                        }
                    ));
                });

            modelBuilder.Entity("IPass.Domain.PasswordDomain.Entities.MemoryType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MemoryTypes", "MEM");
                });

            modelBuilder.Entity("IPass.Domain.PasswordDomain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizationTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentOrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationTypeId");

                    b.HasIndex("ParentOrganizationId");

                    b.ToTable("Organizations", "MEM");
                });

            modelBuilder.Entity("IPass.Domain.PasswordDomain.Entities.OrganizationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OrganizationTypes", "MEM");
                });

            modelBuilder.Entity("IPass.Domain.PasswordDomain.Entities.PinCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("Expiration")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PinCodes", "MEM");
                });

            modelBuilder.Entity("Patika.EF.Shared.AuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuditMetaDataHashPrimaryKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuditMetaDataSchemaTable")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateTimeOffset")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EntityState")
                        .HasColumnType("int");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuditMetaDataHashPrimaryKey", "AuditMetaDataSchemaTable");

                    b.ToTable("Audits", "MEM");
                });

            modelBuilder.Entity("Patika.EF.Shared.AuditMetaDataEntity", b =>
                {
                    b.Property<Guid>("HashPrimaryKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SchemaTable")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReadablePrimaryKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Schema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Table")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HashPrimaryKey", "SchemaTable");

                    b.ToTable("AuditMetaDatas", "MEM");
                });

            modelBuilder.Entity("Patika.Shared.Entities.Loggy.Entities.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ApplicationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Logs", "LOG");
                });

            modelBuilder.Entity("Patika.Shared.Entities.Loggy.Entities.LogDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InputAsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LogType")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputAsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LogId");

                    b.ToTable("LogDetails", "LOG");
                });

            modelBuilder.Entity("IPass.Domain.PasswordDomain.Entities.Memory", b =>
                {
                    b.HasOne("IPass.Domain.PasswordDomain.Entities.EnvironmentType", "EnvironmentType")
                        .WithMany()
                        .HasForeignKey("EnvironmentTypeId");

                    b.HasOne("IPass.Domain.PasswordDomain.Entities.MemoryType", "MemoryType")
                        .WithMany()
                        .HasForeignKey("MemoryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPass.Domain.PasswordDomain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnvironmentType");

                    b.Navigation("MemoryType");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("IPass.Domain.PasswordDomain.Entities.Organization", b =>
                {
                    b.HasOne("IPass.Domain.PasswordDomain.Entities.OrganizationType", "OrganizationType")
                        .WithMany("Organizations")
                        .HasForeignKey("OrganizationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPass.Domain.PasswordDomain.Entities.Organization", "ParentOrganization")
                        .WithMany()
                        .HasForeignKey("ParentOrganizationId");

                    b.Navigation("OrganizationType");

                    b.Navigation("ParentOrganization");
                });

            modelBuilder.Entity("Patika.EF.Shared.AuditEntity", b =>
                {
                    b.HasOne("Patika.EF.Shared.AuditMetaDataEntity", "AuditMetaData")
                        .WithMany("AuditChanges")
                        .HasForeignKey("AuditMetaDataHashPrimaryKey", "AuditMetaDataSchemaTable");

                    b.Navigation("AuditMetaData");
                });

            modelBuilder.Entity("Patika.Shared.Entities.Loggy.Entities.LogDetail", b =>
                {
                    b.HasOne("Patika.Shared.Entities.Loggy.Entities.Log", "Log")
                        .WithMany("Details")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Log");
                });

            modelBuilder.Entity("IPass.Domain.PasswordDomain.Entities.OrganizationType", b =>
                {
                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("Patika.EF.Shared.AuditMetaDataEntity", b =>
                {
                    b.Navigation("AuditChanges");
                });

            modelBuilder.Entity("Patika.Shared.Entities.Loggy.Entities.Log", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
